CREATE TABLE USERS (
    userId VARCHAR(255) PRIMARY KEY NOT NULL ,
    password VARCHAR(255) NOT NULL ,
    email VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL UNIQUE ,
    createTime TIMESTAMP NOT NULL
)