create table article
(
    id            bigint generated by default as identity,
    writer        varchar(255),
    title         varchar(255),
    content       varchar(255),
    creation_time varchar(255),
    view_count    bigint,
    primary key (id)
);