create table article
(
    id           bigint generated by default as identity,
    writer       varchar(255),
    title        varchar(255),
    content      varchar(255),
    creationTime varchar(255),
    viewCount    bigint,
    primary key (id)
);