create table article
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id       VARCHAR(255),
    title         VARCHAR(255),
    content       TEXT,
    creation_time TIMESTAMP,
    view_count    BIGINT,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users (user_id)
);