create table comment
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    article_id     BIGINT NOT NULL,
    user_id       VARCHAR(255) NOT NULL,
    content       TEXT NOT NULL,
    is_modified   BOOLEAN DEFAULT FALSE,
    is_deleted    BOOLEAN DEFAULT FALSE,
    creation_time TIMESTAMP NOT NULL,
    modified_time TIMESTAMP NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (article_id) REFERENCES article (id),
    FOREIGN KEY (user_id) REFERENCES users (user_id)
);