create table users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id       VARCHAR(255) UNIQUE,
    user_password VARCHAR(255),
    user_name     VARCHAR(255),
    user_email    VARCHAR(255),
    PRIMARY KEY (id)
);