create table users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id       VARCHAR(255) NOT NULL UNIQUE,
    user_password VARCHAR(255) NOT NULL,
    user_name     VARCHAR(255) NOT NULL,
    user_email    VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);